#!/bin/sh
-e
sysctl -w 'net.ipv4.ip_forward=1'
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT;
iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT;
iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 8080;
iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 8080;

iptables-save > /etc/iptables.ipv4.nat
echo "To restore:  "
echo "iptables-restore < /etc/iptables.ipv4.nat"
echo "-----------------------------------------"

# /etc/init.d/networking stop && /etc/init.d/networking start
#ifdown -a && ifup -a

/etc/init.d/udhcpd stop && /etc/init.d/udhcpd start
#/etc/init.d/isc-dhcp-server start

/etc/init.d/hostapd stop && /etc/init.d/hostapd start

update-rc.d hostapd enable
update-rc.d udhcpd enable
#update-rc.d isc-dhcp-server enable

return 0
